### ISSUE TITLE
PnP review

### ISSUE THREAD

**Issue by maxisi** [tedwards2412/ripple-paper#6]
Reproducing the action items part from [Geraint's review](https://pnp.ligo.org/P2300025/) here:

Are proper references made to related work within the LSC? - Generally, yes. A few quick comments below. 
  - [x] On the first page you discuss how 'Once potential candidates are found, ...'. It isn't clear if the citations are for the underlying code packages or applications? E.g. the Biwer et al paper used Kombine [Farr et al 2015] and emcee_pt [Vousden et al 16]. So if citing Speagle for Dynesty, then these would be reasonable? 
  - [x] One or two more waveform references needed in introduction. When citing EOB models, please cite Bohe et al [cited later anyway] and Cotesta et al for the latest generation of current EOB models. 
  - [x] Likewise, please cite Garcia-Quiros:2020qpx and Pratten:2020fqn in the general Phenom citations as the latest generation of Phenom models. A lot of these are cited later in the text either way.  
  - [x] For the methods to speed up PE on Page 8, a citation to Leslie:2021ssu would be reasonable as a way to tackle relative binning using waveform models with precession and higher multipoles. 
  - [x] Please add a citation to Cornish:2010kf, as Neil's work was foundational here. 
  - [x] I would also cite Smith:2016qas as the PhenomPv2 ROQ, as this has been very widely used.  

No other actionable comments provided.

**Comment by tedwards2412** [comment]
Think I've added everything now!
